FROM ubuntu:18.04
RUN apt-get update -y
RUN sudo apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN apt-get install -y python-pip python-dev build-essential
