pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile.build'
            args '-p 3006:3006'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'chmod 777 ./jenkins/scripts/kill.sh'
                sh './jenkins/scripts/kill.sh'
                sh 'npm install' 
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'chmod 777 ./jenkins/scripts/test.sh'
        //         sh './jenkins/scripts/test.sh'
        //     }
        // }
        stage('Deliver') {
            steps {
                sh 'chmod 777 ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh'
                // input message: 'Finished using the web site? (Click "Proceed" to continue)'
                // sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
