pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile.build'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
        stage('Test') {
            steps {
                chmod 777 './jenkins/scripts/test.sh'
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}